### ISSUE TITLE
Failure to gyp leveldb.gyp on mac

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/leveldb#8]
```
I tried to generate XCode project file with gyp (latest svn sources r932) but 
get this error:

kjkmacpro:leveldb kkowalczyk$ gyp
Traceback (most recent call last):
  File "/usr/local/bin/gyp", line 18, in <module>
    sys.exit(gyp.main(sys.argv[1:]))
  File "/Library/Python/2.6/site-packages/gyp/__init__.py", line 448, in main
    options.circular_check)
  File "/Library/Python/2.6/site-packages/gyp/__init__.py", line 87, in Load
    depth, generator_input_info, check, circular_check)
  File "/Library/Python/2.6/site-packages/gyp/input.py", line 2224, in Load
    depth, check)
  File "/Library/Python/2.6/site-packages/gyp/input.py", line 379, in LoadTargetBuildFile
    build_file_path)
  File "/Library/Python/2.6/site-packages/gyp/input.py", line 998, in ProcessVariablesAndConditionsInDict
    build_file)
  File "/Library/Python/2.6/site-packages/gyp/input.py", line 1013, in ProcessVariablesAndConditionsInList
    ProcessVariablesAndConditionsInDict(item, is_late, variables, build_file)
  File "/Library/Python/2.6/site-packages/gyp/input.py", line 927, in ProcessVariablesAndConditionsInDict
    expanded = ExpandVariables(value, is_late, variables, build_file)
  File "/Library/Python/2.6/site-packages/gyp/input.py", line 697, in ExpandVariables
    ' in ' + build_file
KeyError: 'Undefined variable library in leveldb.gyp while trying to load 
leveldb.gyp'

I know next to nothing about gyp, but it seems like a problem with lveldb.gyp

I'm on Mac 10.6.7, leveldb is r30, python 2.6.1

```

---

Original issue reported on code.google.com by `kkowalczyk@gmail.com` on 7 Jun 2011 at 4:17

**Comment by GoogleCodeExporter** [comment]
---

Original comment by `tfar...@chromium.org` on 7 Jun 2011 at 2:45
- Changed state: **Accepted**
- Added labels: **OpSys-OSX**

**Comment by GoogleCodeExporter** [comment]
```
leveldb.gyp is interdependent with the Chromium build, and not intended to 
create a standalone project.

It would be possible to create a standalone gyp file that emulates the 
Makefile, though you still end up running an external script (either gyp or 
make) to sync to the latest changes.

I would recommend: pre-build libleveldb.a with make, add it to your project, 
and make sure leveldb/include is in your header search paths.
```

---

Original comment by `ashoema...@gmail.com` on 2 Jul 2011 at 7:42

**Comment by GoogleCodeExporter** [comment]
```
ashoemaker is right, leveldb.gyp was dependent on chromium stuff. So we removed 
it.  It's now in the chromium repository.
```

---

Original comment by `dgrogan@chromium.org` on 5 Aug 2011 at 10:47
- Changed state: **WontFix**
